[[repos]]
repo = "local"

[[repos.hooks]]
id = "fmt"
name = "Format Python sources"
language = "system"
entry = "just fmt"
types = ["python"]
pass_filenames = false

[[repos.hooks]]
id = "lint"
name = "Lint Python sources"
language = "system"
entry = "just lint"
types = ["python"]
pass_filenames = false
