[workspace]
# Publish when a release PR is merged.
release_always = false
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"

[[package]]
name = "olf"
changelog_path = "CHANGELOG.md"
# This package ships a CLI, so library API checks do not apply.
semver_check = false
